stages:
  patches-512-ol-160-mv01-train:
    cmd: python oficial_herdnet/tools/patcher.py data/train 512 512 160 
      data/patches-512-ol-160-m01/train  -csv 
      data/groundtruth/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv && python 
      oficial_herdnet/tools/csv_to_points.py 
      -i data/patches-512-ol-160-m01/train/gt.csv -o data/patches-512-ol-160-m01/train_points_gt.csv
    deps:
    - data/groundtruth/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv
    - data/train/
    - oficial_herdnet/tools/patcher.py
    outs:
    - data/patches-512-ol-160-m01/train_points_gt.csv
    - data/patches-512-ol-160-m01/train/

  patches-512-ol-160-mv01-val:
    cmd: python oficial_herdnet/tools/patcher.py data/val 512 512 160 
      data/patches-512-ol-160-m01/val  -csv 
      data/groundtruth/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv && python 
      oficial_herdnet/tools/csv_to_points.py 
      -i data/patches-512-ol-160-m01/val/gt.csv -o data/patches-512-ol-160-m01/val_points_gt.csv
    deps:
    - data/groundtruth/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv
    - data/val/
    - oficial_herdnet/tools/patcher.py
    outs:
    - data/patches-512-ol-160-m01/val_points_gt.csv
    - data/patches-512-ol-160-m01/val/

  patches-512-ol-160-mv01-test:
    cmd: python oficial_herdnet/tools/patcher.py data/test 512 512 160 
      data/patches-512-ol-160-m01/test  -csv 
      data/groundtruth/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv && python 
      oficial_herdnet/tools/csv_to_points.py 
      -i data/patches-512-ol-160-m01/test/gt.csv -o data/patches-512-ol-160-m01/test_points_gt.csv
    deps:
    - data/groundtruth/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv
    - data/test/
    - oficial_herdnet/tools/patcher.py
    outs:
    - data/patches-512-ol-160-m01/test_points_gt.csv
    - data/patches-512-ol-160-m01/test/

  train-herdnet-v1:
    cmd: python oficial_herdnet/tools/train.py train.training_settings.work_dir=data/models/herdnet_v1/
    deps:
    - data/patches-512-ol-160-m01/train_points_gt.csv
    - data/patches-512-ol-160-m01/train/
    - data/patches-512-ol-160-m01/val_points_gt.csv
    - data/patches-512-ol-160-m01/val/
    outs:
    - data/models/herdnet_v1/