stages:
  patches-512-ol-160-mv01-train:
    cmd: python oficial_herdnet/tools/patcher.py data/train 512 512 160
      data/patches-512-ol-160-m01/train  -csv
      data/groundtruth/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv && python
      oficial_herdnet/tools/csv_to_points.py
      -i data/patches-512-ol-160-m01/train/gt.csv -o data/patches-512-ol-160-m01/train_points_gt.csv
    deps:
    - data/groundtruth/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv
    - data/train/
    - oficial_herdnet/tools/patcher.py
    outs:
    - data/patches-512-ol-160-m01/train_points_gt.csv
    - data/patches-512-ol-160-m01/train/

  patches-512-ol-160-mv01-val:
    cmd: python oficial_herdnet/tools/patcher.py data/val 512 512 160
      data/patches-512-ol-160-m01/val  -csv
      data/groundtruth/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv && python
      oficial_herdnet/tools/csv_to_points.py
      -i data/patches-512-ol-160-m01/val/gt.csv -o data/patches-512-ol-160-m01/val_points_gt.csv
    deps:
    - data/groundtruth/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv
    - data/val/
    - oficial_herdnet/tools/patcher.py
    outs:
    - data/patches-512-ol-160-m01/val_points_gt.csv
    - data/patches-512-ol-160-m01/val/

  patches-512-ol-160-mv01-test:
    cmd: python oficial_herdnet/tools/patcher.py data/test 512 512 160
      data/patches-512-ol-160-m01/test  -csv
      data/groundtruth/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv && python
      oficial_herdnet/tools/csv_to_points.py
      -i data/patches-512-ol-160-m01/test/gt.csv -o data/patches-512-ol-160-m01/test_points_gt.csv
    deps:
    - data/groundtruth/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv
    - data/test/
    - oficial_herdnet/tools/patcher.py
    outs:
    - data/patches-512-ol-160-m01/test_points_gt.csv
    - data/patches-512-ol-160-m01/test/

  train-herdnet-v1:
    cmd: python oficial_herdnet/tools/train.py train.training_settings.work_dir=data/models/herdnet_v1/
    deps:
    - data/patches-512-ol-160-m01/train_points_gt.csv
    - data/patches-512-ol-160-m01/train/
    - data/patches-512-ol-160-m01/val_points_gt.csv
    - data/patches-512-ol-160-m01/val/
    outs:
    - data/models/herdnet_v1/

  fix-headers-train-csv:
    cmd: >
      sed '1s/Image,x1,y1,x2,y2,Label/images,x_min,y_min,x_max,y_max,labels/'
      data/groundtruth/csv/train_big_size_A_B_E_K_WH_WB.csv
      > data/gt-preprocessed/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv
    deps:
      - data/groundtruth/csv/train_big_size_A_B_E_K_WH_WB.csv
    outs:
      - data/gt-preprocessed/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv

  fix-headers-val-csv:
    cmd: >
      sed '1s/Image,x1,y1,x2,y2,Label/images,x_min,y_min,x_max,y_max,labels/'
      data/groundtruth/csv/val_big_size_A_B_E_K_WH_WB.csv
      > data/gt-preprocessed/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv
    deps:
      - data/groundtruth/csv/val_big_size_A_B_E_K_WH_WB.csv
    outs:
      - data/gt-preprocessed/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv

  fix-headers-test-csv:
    cmd: >
      sed '1s/Image,x1,y1,x2,y2,Label/images,x_min,y_min,x_max,y_max,labels/'
      data/groundtruth/csv/test_big_size_A_B_E_K_WH_WB.csv
      > data/gt-preprocessed/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv
    deps:
      - data/groundtruth/csv/test_big_size_A_B_E_K_WH_WB.csv
    outs:
      - data/gt-preprocessed/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv

  patches-512-ol-160-mv0.3-train:
    cmd: >
      python oficial_herdnet/tools/patcher.py
      -csv data/gt-preprocessed/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv
      -min 0.3
      data/train/
      512 512 160
      data/patches-512-ol-160-m0.3/train
    deps:
      - oficial_herdnet/tools/patcher.py
      - data/train/
      - data/gt-preprocessed/csv/train_big_size_A_B_E_K_WH_WB-fixed-header.csv
    outs:
      - data/patches-512-ol-160-m0.3/train

  patches-512-ol-160-mv0.3-val:
    cmd: >
      python oficial_herdnet/tools/patcher.py
      -csv data/gt-preprocessed/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv
      -min 0.3
      data/val/
      512 512 160
      data/patches-512-ol-160-m0.3/val
    deps:
      - oficial_herdnet/tools/patcher.py
      - data/val/
      - data/gt-preprocessed/csv/val_big_size_A_B_E_K_WH_WB-fixed-header.csv
    outs:
      - data/patches-512-ol-160-m0.3/val

  patches-512-ol-160-mv0.3-test:
    cmd: >
      python oficial_herdnet/tools/patcher.py
      -csv data/gt-preprocessed/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv
      -min 0.3
      data/test/
      512 512 160
      data/patches-512-ol-160-m0.3/test
    deps:
      - oficial_herdnet/tools/patcher.py
      - data/test/
      - data/gt-preprocessed/csv/test_big_size_A_B_E_K_WH_WB-fixed-header.csv
    outs:
      - data/patches-512-ol-160-m0.3/test/

  patches-512-ol-160-mv0.3-train-tiny:
    desc: Seleccionar un subconjunto diminuto del conjunto de parches de entrenamiento para hacer tests rápidos
      del flujo de train.
    cmd: >
      mkdir -p data/patches-512-ol-160-m0.3/train-tiny && head -n 200 data/patches-512-ol-160-m0.3/train/gt.csv
      > data/patches-512-ol-160-m0.3/train-tiny/gt-head-200.csv
    deps:
      - data/patches-512-ol-160-m0.3/train/gt.csv
    outs:
      - data/patches-512-ol-160-m0.3/train-tiny/gt-head-200.csv

  patches-512-ol-160-mv0.3-valid-tiny:
    desc: Seleccionar un subconjunto diminuto del conjunto de parches de validación para hacer tests rápidos
      del flujo de train.
    cmd: >
      mkdir -p data/patches-512-ol-160-m0.3/val-tiny &&
      head -n 25 data/patches-512-ol-160-m0.3/val/gt.csv
      > data/patches-512-ol-160-m0.3/val-tiny/gt-head-25.csv
    deps:
      - data/patches-512-ol-160-m0.3/val/gt.csv
    outs:
      - data/patches-512-ol-160-m0.3/val-tiny/gt-head-25.csv

  train-faster-rcnn-hn-trainer:
    desc: Entrenar faster-rcnn via trainer from Herdnet/tools/train.py
    cmd: >
       python oficial_herdnet/tools/train.py  --config-path $PWD/configs/
       train=faster_rcnn_herdnet_trainer
       train.training_settings.work_dir=data/models/faster-rcnn/resnet50-100-epochs-tbl4
       train.training_settings.epochs=100
    deps:
      - configs/train/faster_rcnn_herdnet_trainer.yaml
      - oficial_herdnet/tools/train.py
      - data/patches-512-ol-160-m0.3/train/gt.csv
    outs:
      - data/models/faster-rcnn/resnet50-100-epochs-tbl4

  train-faster-rcnn-resnet-101:
    desc: Entrenar faster-rcnn via trainer from Herdnet/tools/train.py
    cmd: >
      python oficial_herdnet/tools/train.py  --config-path $PWD/configs/
      train=faster_rcnn_herdnet_trainer
      train.wandb_run=faster-rcnn-resnet-101
      train.model.kwargs.architecture=resnet101
      train.training_settings.work_dir=data/models/faster-rcnn/resnet101-100-epochs-tbl4
      train.training_settings.epochs=100
    deps:
      - configs/train/faster_rcnn_herdnet_trainer.yaml
      - oficial_herdnet/tools/train.py
      - data/patches-512-ol-160-m0.3/train/gt.csv
    outs:
      - data/models/faster-rcnn/resnet101-100-epochs-tbl4

  train-faster-rcnn-hn-trainer-tiny:
    desc: >
      Entrenar faster-rcnn via trainer from Herdnet/tools/train.py con datasets mucho mas pequeños para probar
      todo el flujo rápido
    cmd: >
       python oficial_herdnet/tools/train.py  --config-path $PWD/configs/
       train=faster_rcnn_herdnet_trainer
       train.training_settings.work_dir=data/models/faster-rcnn-tiny
       train.training_settings.epochs=3
       train.datasets.train.csv_file=data/patches-512-ol-160-m0.3/train-tiny/gt-head-200.csv
       train.datasets.validate.csv_file=data/patches-512-ol-160-m0.3/val-tiny/gt-head-25.csv
       train.training_settings.print_freq=10
    deps:
      - oficial_herdnet/tools/train.py
      - data/patches-512-ol-160-m0.3/train-tiny/gt-head-200.csv
      - data/patches-512-ol-160-m0.3/val-tiny/gt-head-25.csv
    outs:
      - data/models/faster-rcnn-tiny
