wandb_project: 'Herdnet'
wandb_entity: 'teo-cornell-university'
wandb_run: 'faster-rcnn-tiny'
seed: 17
device_name: 'cuda'
work_dir: "!override-me via command line!"

model:
  name: 'FasterRCNNResNetFPN'
  from_torchvision: False
  load_from: null
  resume_from: null
  kwargs:
    architecture: 'resnet50'
    num_classes: ${train.datasets.num_classes}
    pretrained_backbone: True
    trainable_backbone_layers: 4
    # Class weights in inverse proportion to number of annotations in train :
    # From data_exploration:
    # Alcelaphinae (1) : 1678 -> 1.2
    # Buffalo (2): 1058 -> 1.9
    # Kob (3): 1732 -> 1.16
    # Warthog (4) : 316 -> 6.4
    # Waterbuck (5): 166 -> 12.1
    # Elephant (6): 2012 -> 1.0

    class_weights: [0.1, 1.2, 1.9, 1.16, 6.4, 12.1, 1.0]
    min_size: 512
    max_size: 512

losses: null

datasets:
  img_size: [512,512]
  anno_type: 'bbox'
  num_classes: 7 # including background as class 0
  collate_fn: 'collate_fn'

  # Tomado de: /oficial_herdnet/configs/train/herdnet.yaml
  class_def:
    1: 'Alcelaphinae'
    2: 'Buffalo'
    3: 'Kob'
    4: 'Warthog'
    5: 'Waterbuck'
    6: 'Elephant'

  train:
    name: 'CSVDataset'
    csv_file: 'data/patches-512-ol-160-m0.3/train/gt-head-200.csv'
    root_dir: 'data/patches-512-ol-160-m0.3/train/'

    sampler: null

    albu_transforms:
      HorizontalFlip:
        p: 0.5
      MotionBlur:
        p: 0.5
      Normalize:
        p: 1.0

    end_transforms: null

  validate:
    name: 'CSVDataset'
    csv_file: 'data/patches-512-ol-160-m0.3/val/gt-head-25.csv'
    root_dir: 'data/patches-512-ol-160-m0.3/val/'

    albu_transforms:
      Normalize:
        p: 1.0

    end_transforms: null

training_settings:
  trainer: 'FasterRCNNTrainer'
  valid_freq: 1
  print_freq: 10
  batch_size: 8
  optimizer: 'adam'
  lr: 1e-5
  weight_decay: 0.0005
  auto_lr:
    mode: 'max'
    patience: 10
    threshold: 1e-5
    threshold_mode: 'rel'
    cooldown: 10
    min_lr: 1e-6
    # verbose: True
  warmup_iters: 100
  vizual_fn: null
  epochs: 3
  evaluator:
    name: 'FasterRCNNEvaluator'
    threshold: 0.3
    select_mode: 'max'
    validate_on: 'f1_score'
    kwargs:
      print_freq: 10
  stitcher:
    name: 'FasterRCNNStitcher'
    kwargs:
      overlap: 0
      nms_threshold: 0.5