name: Pre-merge Checks

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  Code-Quality-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
          version: "0.8.x"
      - name: Install Dependencies
        run: |
          uv pip install ruff
          uv pip install pre-commit
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Check pre-commit and ruff versions
        run: uv run pre-commit --version && uv run ruff --version
      - name: Run ruff check
        run: uv run ruff check --config pyproject.toml ./
      - name: Run pre-commit
        run: uv run pre-commit run --hook-stage pre-merge-commit --all-files

  Type-Checking:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
          version: "0.8.x"

      - name: Install Dependencies
        run: |
          uv sync --all-groups
          uv pip install -e "."

      - name: Run Type-checking
        run: |
          export PYTHONPATH="./"
          echo "PYTHONPATH=$PYTHONPATH"
          source .venv/bin/activate          
          poe type-check
